export const MemberState = {
  NEED_VERIFICATION: "NEED_VERIFICATION",
  NEED_TEAM: "NEED_TEAM",
  ACTIVE: "ACTIVE",
} as const;
export type MemberState = (typeof MemberState)[keyof typeof MemberState];

export const University = {
  KYUNGHEE_UNIV: "KYUNGHEE_UNIV",
  AJOU_UNIV: "AJOU_UNIV",
  KYONGGI_UNIV: "KYONGGI_UNIV",
  DANKOOK_UNIV: "DANKOOK_UNIV",
} as const;
export type University = (typeof University)[keyof typeof University];

export const UniversityName: Record<University, string> = {
  KYUNGHEE_UNIV: "경희대학교",
  AJOU_UNIV: "아주대학교",
  KYONGGI_UNIV: "경기대학교",
  DANKOOK_UNIV: "단국대학교",
};

export const EmailDomain: Record<University, string[]> = {
  [University.KYUNGHEE_UNIV]: ["khu.ac.kr"],
  [University.AJOU_UNIV]: ["ajou.ac.kr"],
  [University.KYONGGI_UNIV]: ["kyonggi.ac.kr"],
  [University.DANKOOK_UNIV]: ["dankook.ac.kr"],
};

export const TimeRange = {
  BEFORE: "BEFORE",
  BETWEEN: "BETWEEN",
  AFTER: "AFTER",
} as const;
export type TimeRange = (typeof TimeRange)[keyof typeof TimeRange];

export const LogType = {
  // 참가자 관련 로그
  MEMBER_ATTEND_CHECKED: "MEMBER_ATTEND_CHECKED",
  MEMBER_EMAIL_VERIFICATION_STARTED: "MEMBER_EMAIL_VERIFICATION_STARTED",
  MEMBER_EMAIL_VERIFIED: "MEMBER_EMAIL_VERIFIED",
  MEMBER_STUDENT_INFO_SUBMITTED: "MEMBER_STUDENT_INFO_SUBMITTED",
  MEMBER_PASSWORD_CHANGE_REQUESTED: "MEMBER_PASSWORD_CHANGE_REQUESTED",
  MEMBER_PASSWORD_CHANGED: "MEMBER_PASSWORD_CHANGED",
  MEMBER_REGISTER_COMPLETED: "MEMBER_REGISTER_COMPLETED",
  MEMBER_INVITATION_CREATED: "MEMBER_INVITATION_CREATED",
  MEMBER_INVITATION_CANCELLED: "MEMBER_INVITATION_CANCELLED",
  MEMBER_JOINED_TEAM: "MEMBER_JOINED_TEAM",
  MEMBER_REMOVED_FROM_TEAM: "MEMBER_REMOVED_FROM_TEAM",
  TEAM_CREATED: "TEAM_CREATED",
  TEAM_DELETED: "TEAM_DELETED",
  TEAM_NAME_UPDATED: "TEAM_NAME_UPDATED",
  TEAM_IDEA_UPDATED: "TEAM_IDEA_UPDATED",
  TEAM_PRODUCT_URL_UPDATED: "TEAM_PRODUCT_URL_UPDATED",
  TEAM_ATTACHMENT_UPLOADED: "TEAM_ATTACHMENT_UPLOADED",
  TEAM_ATTACHMENT_DELETED: "TEAM_ATTACHMENT_DELETED",
  TEAM_VOTED: "TEAM_VOTED",

  // 심사위원 관련 로그
  EXAMINER_CREATED: "EXAMINER_CREATED",
  EXAMINER_REMOVED: "EXAMINER_REMOVED",
  EXAMINER_JUDGED: "EXAMINER_JUDGED",
  EXAMINER_REJUDGED: "EXAMINER_REJUDGED",
  EXAMINER_LOGIN: "EXAMINER_LOGIN",

  // 운영진 관련 로그
  MANAGER_TRIED_LOGIN: "MANAGER_TRIED_LOGIN",
  MANAGER_LOGIN: "MANAGER_LOGIN",
  MANAGER_INVITATION_CREATED: "MANAGER_INVITATION_CREATED",
  MANAGER_INVITATION_ACCEPTED: "MANAGER_INVITATION_ACCEPTED",
  MANAGER_INVITATION_CANCELED: "MANAGER_INVITATION_CANCELED",
  NOTICE_CREATED: "NOTICE_CREATED",
  NOTICE_UPDATED: "NOTICE_UPDATED",
  NOTICE_DELETED: "NOTICE_DELETED",
  MANAGER_SENT_SMS: "MANAGER_SENT_SMS",
  MANAGER_CHANGE_TEAM_IDEA: "MANAGER_CHANGE_TEAM_IDEA",
  MANAGER_SET_TEAM_PRIZE: "MANAGER_SET_TEAM_PRIZE",
  MANAGER_DELETED_TEAM: "MANAGER_DELETED_TEAM",
} as const;
export type LogType = (typeof LogType)[keyof typeof LogType];

export const Group = {
  A: "A",
  B: "B",
} as const;
export type Group = (typeof Group)[keyof typeof Group];
